<paste log output from Kubernetes-mediated prediction, here>
(.devops) voclabs:~/environment/project4-udacity-operationalize-ml (master) $ ./run_kubernetes.sh
Error from server (AlreadyExists): pods "sklearn-api" already exists
NAME          READY   STATUS    RESTARTS   AGE
sklearn-api   1/1     Running   0          19m
Forwarding from 127.0.0.1:8080 -> 80
Forwarding from [::1]:8080 -> 80
Handling connection for 8080

(.devops) voclabs:~/environment/project4-udacity-operationalize-ml (master) $ kubectl logs sklearn-api
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 234-179-977
[2022-07-30 09:18:08,914] INFO in app: JSON payload:
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}} 
[2022-07-30 09:18:08,929] INFO in app: Inference payload DataFrame:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-07-30 09:18:08,939] INFO in app: Scaling Payload:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-07-30 09:18:08,943] INFO in app: Prediction:
[20.35373177134412]